import type { JSX } from 'react';
import Head from 'next/head';
import Navbar from '~/components/navbar';
import Header from '~/components/header';
import EpisodesList from '~/components/episodesList';

export default function Episodes(): JSX.Element {
	return (
		<>
			<Head>
				<title>Episodes</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Navbar />
				<Header imageName="episodes" />
				<EpisodesList />
			</main>
		</>
	);
}
