import Head from 'next/head';
import Characters from '~/components/characters';
import Navbar from '~/components/navbar';
import Header from '~/components/header';

const Home = () => (
	<>
		<Head>
			<title>Rick and Morty</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<main>
			<Navbar />
			<Header imageName="characters" />
			<Characters />
		</main>
	</>
);

export default Home;
