import Head from 'next/head';
import Characters from '~/components/characters';

const Home = () => (
	<>
		<Head>
			<title>Rick and Morty</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<main>
			<header>
				<h1>Rick and Morty</h1>
				<h2>Welcome!</h2>
			</header>
			<Characters />
		</main>
	</>
);

export default Home;
