import type { JSX } from 'react';
import Head from 'next/head';
import Navbar from '~/components/navbar';
import Header from '~/components/header';
import LocationsList from '~/components/locationsList';

export default function Locations(): JSX.Element {
	return (
		<>
			<Head>
				<title>Locations</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Navbar />
				<Header imageName="locations" />
				<LocationsList />
			</main>
		</>
	);
}
