import type { JSX } from 'react';
import { Character } from '~/utils/types';
import { useSearchParams } from 'next/navigation';
import { useState, useEffect} from 'react';
import CharacterDetails from '~/components/characterDetails';
import Head from 'next/head';
import Navbar from '~/components/navbar';
import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';

export default function CharacterDetail(): JSX.Element {
	const searchParams = useSearchParams();
	const id = searchParams.get('id');

	const [item, setItem] = useState<Character>();
	const [loading, setLoading] = useState<boolean>(false);
	const [error, setError] = useState<string | null>(null);

	useEffect(() => {
		const fetchData = async () => {
			try {
				setLoading(true);
				const response = await fetch(
					`https://rickandmortyapi.com/api/character/${id}`,
				);

				if (!response.ok) throw new Error('No Character Found');

				const data = await response.json();

				setItem(data);
			} catch (err) {
				setError(err instanceof Error ? err.message : 'Unknown error');
			} finally {
				setLoading(false);
			}
		};

		fetchData();
	}, []);

	return (
		<>
			<Head>
				<title>Character Details</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Navbar />
				<Link href={{}}>
					<div className="goBackSection">
						<ArrowLeft size={23} />
						<p style={{ fontWeight: 600, fontSize: 'x-large' }}>GO BACK</p>
					</div>
				</Link>
				<CharacterDetails item={item} />
			</main>
		</>
	);
}
